[build]
builder = "nixpacks"

[deploy]
startCommand = "echo 'Monorepo - deploy individual services'"

# 后端服务配置
[services.backend]
source = "backend"
buildCommand = "pip install -r requirements.txt"
startCommand = "python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT"

# 前端服务配置  
[services.frontend]
source = "frontend"
buildCommand = "npm ci && npm run build"
startCommand = "serve -s build -l 3000"
