import 'dart:math';

import 'package:flutter/material.dart';

/// 首页 Linker 思考云朵语录（按中英文区分）
class LinkerQuotes {
  LinkerQuotes._();

  static final _random = Random();

  /// 简短、温暖或有哲理的语录（中文）
  static const List<String> zh = [
    '今天也要加油呀～',
    '你比想象中更棒。',
    '小步前进也是进步。',
    '做自己的光 ✨',
    '休息一下再出发～',
    '每一天都是新的开始。',
    '慢慢来，比较快。',
    '你值得被温柔以待。',
    '你永远可以重写你的故事。',
    '今天也要开心呀～',
    '小小的鼓励，大大的力量。',
    'Linker 随时在你身边 💙',
    '好事正在发生。',
    '此刻即礼物。',
    '你已在路上了。',
    '温柔是种力量。',
    '先照顾好自己。',
    '今天也谢谢自己。',
    '不必完美，够好就好。',
    '选择比努力更靠近你。',
    '慢一点，稳一点。',
    '你本来就很值得。',
    '相信过程。',
    '简单一点，开心一点。',
    '今天的小确幸也算成就。',
    '你并不孤单。',
    '允许自己休息。',
    '心向光，路自亮。',
    '小日子，大幸福。',
    '千里之行，始于足下。',
    '天道酬勤。',
    '静水流深。',
    '但行好事，莫问前程。',
    '念念不忘，必有回响。',
    '山高路远，见世界也找自己。',
    '种一棵树最好的时间是十年前，其次是现在。',
    '凡心所向，素履以往。',
    '温柔半两，从容一生。',
    '人生没有白走的路。',
    '愿你眼有星辰，心有山海。',
    '知足常乐。',
    '行到水穷处，坐看云起时。',
    '你若盛开，清风自来。',
    '与其抱怨黑暗，不如提灯前行。',
    '生活明朗，万物可爱。',
    '保持热爱，奔赴山海。',
    '今日事，今日毕。',
    '心有所期，忙而不茫。',
    '不赶路，感受路。',
    '做喜欢的事，爱想爱的人。',
    '日子平淡，好在我喜欢。',
    '向前看，别回头。',
    '愿你心中有花，手里有剑。',
    '简单生活，清醒温柔。',
    '把今天过好，明天不会差。',
    '你很好，我也很好。',
    '少想一点，多做一点。',
    '人间值得，你也值得。',
    '愿你所遇皆温暖。',
    '不卑不亢，清澈生活。',
    '把期望降低，把依赖变少。',
    '好好生活，慢慢相遇。',
    '愿你有梦为马，随处可栖。',
    '愿你成为自己的太阳。',
    '不辜负今天，才能遇见明天。',
    '愿你眼里有光，心里有海。',
    '世界很大，你很好。',
    '愿你被世界温柔以待。',
    '愿你心中有景，花香满径。',
    '愿你一路繁花相送。',
    '愿你永远年轻，永远热泪盈眶。',
    '愿你心中有梦，脚下有路。',
    '愿你遇良人，暖色浮余生。',
    '愿你以渺小启程，以伟大结尾。',
    '愿你眼里有星辰大海。',
    '愿你心中有暖，眼中有光。',
    '愿你一生努力，一生被爱。',
    '愿你想要的都拥有，得不到的都释怀。',
    '愿你三冬暖，愿你春不寒。',
    '愿你所有快乐无需假装。',
    '愿你此生尽兴，赤诚善良。',
    '愿你有盔甲也有软肋。',
    '愿你走过一路难堪，依旧落落大方。',
    '愿你永远有颗少女心。',
    '愿你活成自己想成为的样子。',
    '愿你无忧无虑，平安喜乐。',
    '愿你温柔且坚定。',
    '愿你眼里有光，活成自己想要的模样。',
    '愿你心中有梦，眼里有光。',
    '愿你被这个世界温柔以待。',
    '愿你一生清澈明朗。',
    '愿你心中有景，花香满径。',
    '愿你永远被爱，永远可爱。',
    '愿你心中有梦，脚下有路，眼里有光。',
    '愿你一生温暖纯良，不舍爱与自由。',
    '愿你心中有光，脚下有路。',
    '愿你永远相信美好。',
  ];

  /// 简短、温暖或有哲理的语录（英文）
  static const List<String> en = [
    'Every day is a new beginning.',
    'Small steps still move you forward.',
    'Be your own light ✨',
    'You deserve to be treated gently.',
    "It's never too late to start.",
    'Linker is here for you 💙',
    'Good things are on the way.',
    'The present is a gift.',
    'You are already enough.',
    'Kindness is strength.',
    'Take care of yourself first.',
    'Trust the process.',
    'Progress over perfection.',
    'Slow down, stay steady.',
    'You are not alone.',
    'Rest is part of the journey.',
    'Choose joy today.',
    'Little wins count.',
    'Be gentle with yourself.',
    'Good things take time.',
    'You matter.',
    'One step at a time.',
    'Hope is a good thing.',
    'Breathe. You are doing fine.',
    'The best time to plant a tree was 20 years ago. The second best is now.',
    'Stay hungry, stay foolish.',
    'Think different.',
    'Where there is a will, there is a way.',
    'Actions speak louder than words.',
    'Every cloud has a silver lining.',
    'Life is what happens when you are busy making other plans.',
    'The journey of a thousand miles begins with a single step.',
    'Carpe diem.',
    'What we think, we become.',
    'Be the change you wish to see.',
    'It is during our darkest moments that we must focus to see the light.',
    'The only impossible journey is the one you never begin.',
    'Do what you can, with what you have, where you are.',
    'Happiness is not something ready made. It comes from your own actions.',
    'In the middle of difficulty lies opportunity.',
    'Believe you can and you are halfway there.',
    'The secret of getting ahead is getting started.',
    'When one door closes, another opens.',
    'Fall seven times, stand up eight.',
    'No pain, no gain.',
    'Practice makes perfect.',
    'Time heals all wounds.',
    'Better late than never.',
    'Nothing is impossible.',
    'Live and let live.',
    'All you need is love.',
    'Dream big, start small.',
    'Less is more.',
    'Quality over quantity.',
    'Patience is a virtue.',
    'Fortune favors the bold.',
    'Learn from yesterday, live for today.',
    'Today is the first day of the rest of your life.',
    'Bloom where you are planted.',
    'Let it be.',
    'Keep it simple.',
    'Embrace the journey.',
    'Dare to dream.',
    'Choose courage over comfort.',
    'You are braver than you believe.',
    'Start where you are. Use what you have.',
    'The best is yet to come.',
    'Make today count.',
    'Rise and shine.',
    'Stay curious.',
    'Be present.',
    'Trust the timing of your life.',
    'Let your soul shine.',
    'You are enough.',
    'Shine on.',
    'Keep going.',
    'Never give up.',
    'Believe in yourself.',
    'Follow your heart.',
    'Live with intention.',
    'Find joy in the ordinary.',
    'Celebrate small victories.',
    'Be kind to your mind.',
    'You got this.',
    'Tomorrow is a new day.',
    'Keep your head up.',
    'Stay true to yourself.',
    'Make it happen.',
    'Create your own sunshine.',
    'Dance like nobody is watching.',
    'Leave a little sparkle wherever you go.',
    'You are your only limit.',
    'Radiate kindness.',
  ];

  static String randomQuote(Locale locale) {
    final isZh = locale.languageCode.toLowerCase().startsWith('zh');
    final list = isZh ? zh : en;
    return list[_random.nextInt(list.length)];
  }
}
