-- 迁移 230：种子达人团队收款与责任声明 (expert_terms) v1.0
-- 依赖：076 (legal_documents 表)
-- 在达人团队申请页 + 团队管理页提供独立的"收款与责任声明"入口；
-- 申请提交时由 owner 勾选记录到 expert_applications.agreed_terms_version (migration 229)。
-- 幂等：使用 ON CONFLICT (type, lang) DO UPDATE。

-- ========== 中文 (zh) ==========
INSERT INTO legal_documents (type, lang, content_json, version, effective_at)
VALUES ('expert_terms', 'zh', $EXPERT_ZH$
{
  "title": "达人团队收款与责任声明",
  "lastUpdated": "最后更新：2026-05-08",
  "version": "版本：v1.0",
  "effectiveDate": "生效日期：2026-05-08",
  "intro": "本声明适用于在 Link²Ur 平台创建的所有达人团队 (Expert Team)。本平台为 C2C 协作平台，不为团队提供独立的公司收款主体或资金托管服务。所有团队收款由团队 Owner 以个人身份代收，Owner 与团队成员之间的内部约定不影响本声明对外效力。提交达人团队申请，即视为已阅读、理解并接受本声明全文。",
  "payoutHolder": "收款主体说明：你的团队接单产生的全部收入，均直接进入团队 Owner 的个人 Stripe 账户（由你在创建团队时绑定）。Link²Ur 不持有、不托管、不代付任何资金；团队 ID 不对应独立金融账户。团队公开页将向买家展示「本团队收款由 Owner 以个人身份代收」字样；Owner 转让时，代收人随之变更，历史已结算交易归属不可追溯。",
  "internalSplit": "内部分账自负：团队成员之间的酬劳、分成、奖金等内部分配，完全由你与成员自行约定。Link²Ur 不参与分账、不留存分账记录、不调解因分账产生的纠纷。如发生争议，你需自行依据成员协议、聊天记录或其他证据与对方协商，必要时通过司法或仲裁途径解决。",
  "taxResponsibility": "税务自负：你需就个人 Stripe 账户产生的全部收入，自行向所在司法辖区主管机关（包括但不限于英国 HMRC、中国税务机关等）申报并缴纳应纳税款，包括所得税、增值税（VAT，英国年营业额超过 £90,000 时强制注册）及任何其他法定税费。Link²Ur 仅作为撮合平台，不代扣代缴，不出具完税凭证；平台向你披露的交易记录不构成税务建议。",
  "stripeTerms": "Stripe 服务条款：平台目前仅支持 Stripe Express 个人账户接入。你确认你的实际经营活动符合 Stripe 服务条款（https://stripe.com/legal/connect-account）关于个人账户的限制。若 Stripe 因合规审查、风控判定、KYC/KYB 资料缺失等原因冻结、限制、保留或关停你的账户，由你直接与 Stripe 协商解决；Link²Ur 不就因此产生的资金延迟或损失承担责任。",
  "volumeNotice": "流水提示与升级：平台会按团队近 30 天结算流水自动监测——超过 £5,000 时通过站内信与邮件提示你考虑切换至对公收款方式；超过 £20,000 时，平台保留要求你在合理期限内提供企业资质材料、暂停新接单或限制部分功能的权利。该阈值仅为风险提示，不构成法律或税务上的强制门槛；具体合规义务以你所在司法辖区法律为准。",
  "contactUs": "如对本声明有疑问，请通过应用内「我的 → 帮助中心 → 联系客服」或邮件 info@link2ur.com 与我们联系。客服工作时间为周一至周五 09:00-18:00（英国时间）。",
  "importantNotice": "本声明由 Link²Ur 平台制定并保留最终解释权。本声明可能因业务调整或法律法规变化而更新，更新后将在应用内公示并以最新版本为准。继续使用平台达人团队功能视为接受最新版本声明。"
}
$EXPERT_ZH$, 'v1.0', '2026-05-08'::date)
ON CONFLICT (type, lang) DO UPDATE
SET content_json = EXCLUDED.content_json,
    version = EXCLUDED.version,
    effective_at = EXCLUDED.effective_at,
    updated_at = NOW();

-- ========== English (en) ==========
INSERT INTO legal_documents (type, lang, content_json, version, effective_at)
VALUES ('expert_terms', 'en', $EXPERT_EN$
{
  "title": "Expert Team Payout & Liability Notice",
  "lastUpdated": "Last updated: 2026-05-08",
  "version": "Version: v1.0",
  "effectiveDate": "Effective date: 2026-05-08",
  "intro": "This notice applies to all Expert Teams created on the Link²Ur platform. Link²Ur is a peer-to-peer marketplace; it does not provide an independent corporate payee or fund-custody service for your team. All team earnings are received by the team Owner in a personal capacity; any internal arrangement between the Owner and team members does not affect the third-party-facing position set out below. Submitting an Expert Team application is deemed to constitute your acknowledgement and acceptance of this notice in full.",
  "payoutHolder": "Payout holder. All revenue generated by your team's orders flows directly into the personal Stripe account of the team Owner (linked when the team is created). Link²Ur does not hold, custody or disburse any funds; the team ID does not correspond to a separate financial account. Your team's public page will display 'Payments to this team are received by {Owner} in a personal capacity' to buyers. When ownership is transferred, the payout holder updates accordingly; historical settled transactions cannot be retroactively reattributed.",
  "internalSplit": "Internal split is your responsibility. The allocation of fees, splits, bonuses or any other distribution between team members is wholly a matter between you and your members. Link²Ur does not participate in the split, retain split records, or mediate disputes arising from internal distribution. In the event of a dispute, you must resolve it directly with the other party based on member agreements, chat records or other evidence, and through judicial or arbitral channels where necessary.",
  "taxResponsibility": "Tax is your responsibility. You are solely responsible for declaring and paying all taxes due on the income received into your personal Stripe account to the competent authority of your jurisdiction (including but not limited to HMRC in the UK and the tax authority in China), including income tax, VAT (mandatory registration in the UK once annual turnover exceeds £90,000) and any other statutory levies. Link²Ur is a matchmaking platform only; it does not withhold or remit tax on your behalf and does not issue tax receipts. Transaction records disclosed by the platform do not constitute tax advice.",
  "stripeTerms": "Stripe terms. The platform currently only supports onboarding via Stripe Express personal accounts. You confirm that your actual business activity complies with the personal-account limitations of the Stripe Connected Account Agreement (https://stripe.com/legal/connect-account). If Stripe freezes, limits, withholds or terminates your account due to compliance review, risk-control determination, missing KYC/KYB documentation or any other reason, you must resolve the matter directly with Stripe. Link²Ur is not liable for any resulting fund delay or loss.",
  "volumeNotice": "Volume notice & upgrade. The platform automatically monitors your team's settled volume over the trailing 30 days: when it exceeds £5,000 we will notify you (in-app and by email) to consider switching to a corporate-payout arrangement; when it exceeds £20,000 the platform reserves the right to require you, within a reasonable period, to provide corporate-entity documentation, suspend new orders, or restrict specific features. These thresholds are risk indicators only; they do not constitute a statutory legal or tax threshold — your specific compliance obligations are governed by the laws of your own jurisdiction.",
  "contactUs": "If you have any questions about this notice, please contact us via 'Profile → Help Centre → Contact Support' in the app, or by email at info@link2ur.com. Support hours are Monday to Friday, 09:00-18:00 (UK time).",
  "importantNotice": "This notice is issued by Link²Ur, which retains final right of interpretation. The notice may be updated due to business changes or changes in law, and the latest version will be published in the app and prevail. Continued use of the Expert Team feature constitutes acceptance of the latest version of this notice."
}
$EXPERT_EN$, 'v1.0', '2026-05-08'::date)
ON CONFLICT (type, lang) DO UPDATE
SET content_json = EXCLUDED.content_json,
    version = EXCLUDED.version,
    effective_at = EXCLUDED.effective_at,
    updated_at = NOW();

-- 验证
-- SELECT type, lang, version, effective_at FROM legal_documents WHERE type = 'expert_terms';
-- 期望：2 行 (zh + en)，version='v1.0'，effective_at='2026-05-08'
