-- 任务达人信息修改审核申请表
-- 执行前请先备份数据库

CREATE TABLE IF NOT EXISTS task_expert_profile_update_requests (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    expert_id VARCHAR(8) NOT NULL REFERENCES task_experts(id) ON DELETE CASCADE,
    -- 待修改的字段
    new_expert_name VARCHAR(100),  -- 新的名字
    new_bio TEXT,  -- 新的简介
    new_avatar TEXT,  -- 新的头像
    -- 审核相关
    status VARCHAR(20) DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),  -- pending, approved, rejected
    reviewed_by VARCHAR(5) REFERENCES admin_users(id),  -- 审核管理员ID
    reviewed_at TIMESTAMPTZ,  -- 审核时间
    review_comment TEXT,  -- 审核意见
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 索引
CREATE INDEX IF NOT EXISTS idx_profile_update_requests_expert_id ON task_expert_profile_update_requests(expert_id);
CREATE INDEX IF NOT EXISTS idx_profile_update_requests_status ON task_expert_profile_update_requests(status);
CREATE INDEX IF NOT EXISTS idx_profile_update_requests_reviewed_by ON task_expert_profile_update_requests(reviewed_by);

-- 部分唯一索引：确保一个任务达人只能有一个待审核的修改请求
CREATE UNIQUE INDEX IF NOT EXISTS uq_profile_update_pending
ON task_expert_profile_update_requests (expert_id, status)
WHERE status = 'pending';

