-- 任务达人功能数据库迁移脚本
-- 执行前请先备份数据库

-- ==================== 任务达人申请表 ====================
CREATE TABLE IF NOT EXISTS task_expert_applications (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id VARCHAR(8) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    application_message TEXT,  -- 申请说明
    status VARCHAR(20) DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),  -- pending, approved, rejected
    reviewed_by VARCHAR(5) REFERENCES admin_users(id),  -- 审核管理员ID
    reviewed_at TIMESTAMPTZ,  -- 审核时间
    review_comment TEXT,  -- 审核意见
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 索引
CREATE INDEX IF NOT EXISTS idx_task_expert_applications_user_id ON task_expert_applications(user_id);
CREATE INDEX IF NOT EXISTS idx_task_expert_applications_status ON task_expert_applications(status);
CREATE INDEX IF NOT EXISTS idx_task_expert_applications_reviewed_by ON task_expert_applications(reviewed_by);

-- 部分唯一索引：确保一个用户只能有一个待审核的申请
CREATE UNIQUE INDEX IF NOT EXISTS uq_expert_app_pending
ON task_expert_applications (user_id, status)
WHERE status = 'pending';

-- ==================== 任务达人表 ====================
CREATE TABLE IF NOT EXISTS task_experts (
    id VARCHAR(8) PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,  -- 与用户ID相同
    expert_name VARCHAR(100),  -- 任务达人名称（可不同于用户名）
    bio TEXT,  -- 个人简介
    avatar TEXT,  -- 头像（可覆盖用户默认头像，使用TEXT以支持长CDN URL）
    status VARCHAR(20) DEFAULT 'active' CHECK (status IN ('active', 'inactive', 'suspended')),  -- active, inactive, suspended
    rating DECIMAL(3,2) DEFAULT 0.00 CHECK (rating >= 0.00 AND rating <= 5.00),  -- 平均评分（0.00-5.00）
    total_services INTEGER DEFAULT 0,  -- 服务总数
    completed_tasks INTEGER DEFAULT 0,  -- 完成任务数
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    approved_by VARCHAR(5) REFERENCES admin_users(id),  -- 批准的管理员ID
    approved_at TIMESTAMPTZ  -- 批准时间
);

-- 索引
CREATE INDEX IF NOT EXISTS idx_task_experts_status ON task_experts(status);
CREATE INDEX IF NOT EXISTS idx_task_experts_rating ON task_experts(rating);

-- ==================== 任务达人服务菜单表 ====================
CREATE TABLE IF NOT EXISTS task_expert_services (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    expert_id VARCHAR(8) NOT NULL REFERENCES task_experts(id) ON DELETE CASCADE,
    service_name VARCHAR(200) NOT NULL,  -- 服务名称
    description TEXT NOT NULL,  -- 服务描述
    images JSONB,  -- JSON数组，存储图片URL列表（使用PostgreSQL JSONB类型）
    base_price DECIMAL(12, 2) NOT NULL,  -- 基础价格
    currency VARCHAR(3) DEFAULT 'GBP' CHECK (currency ~ '^[A-Z]{3}$'),  -- 货币类型（ISO 4217格式）
    status VARCHAR(20) DEFAULT 'active' CHECK (status IN ('active', 'inactive')),  -- active, inactive
    display_order INTEGER DEFAULT 0,  -- 显示顺序
    view_count INTEGER DEFAULT 0,  -- 浏览次数
    application_count INTEGER DEFAULT 0,  -- 申请次数
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 索引
CREATE INDEX IF NOT EXISTS idx_task_expert_services_expert_id ON task_expert_services(expert_id);
CREATE INDEX IF NOT EXISTS idx_task_expert_services_status ON task_expert_services(status);
CREATE INDEX IF NOT EXISTS idx_task_expert_services_expert_status ON task_expert_services(expert_id, status);

-- ==================== 服务申请表 ====================
CREATE TABLE IF NOT EXISTS service_applications (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    service_id INTEGER NOT NULL REFERENCES task_expert_services(id) ON DELETE CASCADE,
    applicant_id VARCHAR(8) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    expert_id VARCHAR(8) NOT NULL REFERENCES task_experts(id) ON DELETE CASCADE,
    application_message TEXT,  -- 申请留言
    negotiated_price DECIMAL(12, 2),  -- 用户提出的议价价格（可选）
    expert_counter_price DECIMAL(12, 2),  -- 任务达人提出的再次议价价格（可选）
    currency VARCHAR(3) DEFAULT 'GBP' CHECK (currency ~ '^[A-Z]{3}$'),  -- 货币类型（ISO 4217格式）
    status VARCHAR(20) DEFAULT 'pending' CHECK (status IN ('pending', 'negotiating', 'price_agreed', 'approved', 'rejected', 'cancelled')),  -- pending, negotiating, price_agreed, approved, rejected, cancelled
    final_price DECIMAL(12, 2),  -- 最终确定的价格（创建任务时使用）
    task_id INTEGER REFERENCES tasks(id) ON DELETE SET NULL,  -- 关联的任务ID（任务删除时设为NULL，建议任务不物理删除）
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    approved_at TIMESTAMPTZ,  -- 同意时间
    rejected_at TIMESTAMPTZ,  -- 拒绝时间
    price_agreed_at TIMESTAMPTZ  -- 价格达成一致的时间
);

-- 索引
CREATE INDEX IF NOT EXISTS idx_service_applications_service_id ON service_applications(service_id);
CREATE INDEX IF NOT EXISTS idx_service_applications_applicant_id ON service_applications(applicant_id);
CREATE INDEX IF NOT EXISTS idx_service_applications_expert_id ON service_applications(expert_id);
CREATE INDEX IF NOT EXISTS idx_service_applications_status ON service_applications(status);
CREATE INDEX IF NOT EXISTS idx_service_applications_task_id ON service_applications(task_id);
-- 常用筛选列的索引（可选，根据查询路径决定）
CREATE INDEX IF NOT EXISTS idx_service_applications_price_agreed_at ON service_applications(price_agreed_at) WHERE price_agreed_at IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_service_applications_approved_at ON service_applications(approved_at) WHERE approved_at IS NOT NULL;

-- 部分唯一索引：确保同一用户对同一服务只能有一个待处理的申请
CREATE UNIQUE INDEX IF NOT EXISTS uq_service_app_pending_combo
ON service_applications (service_id, applicant_id, status)
WHERE status IN ('pending', 'negotiating', 'price_agreed');

-- 分析表，更新统计信息
ANALYZE task_expert_applications;
ANALYZE task_experts;
ANALYZE task_expert_services;
ANALYZE service_applications;

