"""咨询相关错误码常量。供路由统一使用,客户端据此做 l10n。

每个常量的字符串值与常量名相同,方便 grep 与序列化。新加错误码时:
  1. 在此文件追加常量
  2. 在 iOS/Android/Flutter 的 error_localizer 扩展里加本地化映射
  3. 在 docs/superpowers/specs/2026-04-17-consultation-fixes-design.md 错误码表同步

注意:
  - 语义上"冲突/已存在"走 409,"未找到"走 404,"状态机不允许"走 400,"身份不足"走 403。
  - 实际 status_code 由路由决定,此文件只提供 error_code 命名空间。
"""

CONSULTATION_ALREADY_EXISTS = "CONSULTATION_ALREADY_EXISTS"
CONSULTATION_NOT_FOUND = "CONSULTATION_NOT_FOUND"
CONSULTATION_CLOSED = "CONSULTATION_CLOSED"
SERVICE_NOT_FOUND = "SERVICE_NOT_FOUND"
SERVICE_INACTIVE = "SERVICE_INACTIVE"
TASK_NOT_FOUND = "TASK_NOT_FOUND"
EXPERT_TEAM_NOT_FOUND = "EXPERT_TEAM_NOT_FOUND"
EXPERT_TEAM_INACTIVE = "EXPERT_TEAM_INACTIVE"
CANNOT_CONSULT_SELF = "CANNOT_CONSULT_SELF"
NOT_SERVICE_OWNER = "NOT_SERVICE_OWNER"
NOT_TEAM_MEMBER = "NOT_TEAM_MEMBER"
INSUFFICIENT_TEAM_ROLE = "INSUFFICIENT_TEAM_ROLE"
INVALID_STATUS_TRANSITION = "INVALID_STATUS_TRANSITION"
PRICE_OUT_OF_RANGE = "PRICE_OUT_OF_RANGE"
