"""Initial migration: create all tables

Revision ID: 087ca9fb512c
Revises: 
Create Date: 2025-09-24 12:00:44.358693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '087ca9fb512c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 安全删除和创建索引（如果存在/不存在）
    from sqlalchemy import text
    connection = op.get_bind()
    
    def safe_drop_index(index_name, table_name):
        """安全删除索引（使用 SAVEPOINT）"""
        savepoint_name = f"sp_drop_{index_name.replace('.', '_').replace('-', '_')}"
        try:
            connection.execute(text(f"SAVEPOINT {savepoint_name}"))
            # 直接尝试删除索引
            op.drop_index(op.f(index_name), table_name=table_name)
            connection.execute(text(f"RELEASE SAVEPOINT {savepoint_name}"))
        except Exception:
            # 回滚到保存点，继续执行（索引可能不存在，这是正常的）
            try:
                connection.execute(text(f"ROLLBACK TO SAVEPOINT {savepoint_name}"))
            except:
                pass
    
    def safe_create_index(index_name, table_name, columns, unique=False):
        """安全创建索引（使用 SAVEPOINT 避免事务失败）"""
        savepoint_name = f"sp_{index_name.replace('.', '_').replace('-', '_')}"
        try:
            connection.execute(text(f"SAVEPOINT {savepoint_name}"))
            # 直接尝试创建索引
            op.create_index(op.f(index_name), table_name, columns, unique=unique)
            connection.execute(text(f"RELEASE SAVEPOINT {savepoint_name}"))
        except Exception as e:
            # 回滚到保存点，继续执行
            try:
                connection.execute(text(f"ROLLBACK TO SAVEPOINT {savepoint_name}"))
            except:
                pass
            # 如果是索引已存在的错误，忽略（这是正常情况）
            error_str = str(e).lower()
            if not any(keyword in error_str for keyword in ["already exists", "duplicate", "relation"]):
                # 其他错误需要记录，但不中断迁移
                pass
    
    # 安全删除 customer_service_chats 表的索引
    safe_drop_index('idx_customer_service_chats_is_ended', 'customer_service_chats')
    safe_drop_index('idx_customer_service_chats_service_id', 'customer_service_chats')
    safe_drop_index('idx_customer_service_chats_user_id', 'customer_service_chats')
    
    # 安全创建索引
    safe_create_index('ix_customer_service_chats_id', 'customer_service_chats', ['id'])
    
    # 安全删除 customer_service_messages 表的索引
    safe_drop_index('idx_customer_service_messages_chat_id', 'customer_service_messages')
    safe_drop_index('idx_customer_service_messages_created_at', 'customer_service_messages')
    
    # 安全创建索引
    safe_create_index('ix_customer_service_messages_id', 'customer_service_messages', ['id'])
    
    # 安全创建外键（如果不存在）
    def safe_create_foreign_key(constraint_name, source_table, referent_table, local_cols, remote_cols):
        """安全创建外键，如果已存在则跳过（使用 SAVEPOINT）"""
        savepoint_name = f"sp_fk_{source_table}_{constraint_name or '_'.join(local_cols)}".replace('.', '_').replace('-', '_')
        try:
            connection.execute(text(f"SAVEPOINT {savepoint_name}"))
            op.create_foreign_key(constraint_name, source_table, referent_table, local_cols, remote_cols)
            connection.execute(text(f"RELEASE SAVEPOINT {savepoint_name}"))
        except Exception as e:
            # 回滚到保存点，继续执行
            try:
                connection.execute(text(f"ROLLBACK TO SAVEPOINT {savepoint_name}"))
            except:
                pass
            # 如果是外键已存在的错误，忽略（这是正常情况）
            error_str = str(e).lower()
            if not any(keyword in error_str for keyword in ["already exists", "duplicate", "constraint"]):
                # 其他错误需要记录，但不中断迁移
                pass
    
    safe_create_foreign_key(None, 'messages', 'users', ['sender_id'], ['id'])
    safe_create_foreign_key(None, 'messages', 'users', ['receiver_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_index(op.f('ix_customer_service_messages_id'), table_name='customer_service_messages')
    op.create_index(op.f('idx_customer_service_messages_created_at'), 'customer_service_messages', ['created_at'], unique=False)
    op.create_index(op.f('idx_customer_service_messages_chat_id'), 'customer_service_messages', ['chat_id'], unique=False)
    op.drop_index(op.f('ix_customer_service_chats_id'), table_name='customer_service_chats')
    op.create_index(op.f('idx_customer_service_chats_user_id'), 'customer_service_chats', ['user_id'], unique=False)
    op.create_index(op.f('idx_customer_service_chats_service_id'), 'customer_service_chats', ['service_id'], unique=False)
    op.create_index(op.f('idx_customer_service_chats_is_ended'), 'customer_service_chats', ['is_ended'], unique=False)
    # ### end Alembic commands ###
