"""Initial migration: create all tables

Revision ID: 087ca9fb512c
Revises: 
Create Date: 2025-09-24 12:00:44.358693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '087ca9fb512c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 安全删除和创建索引（如果存在/不存在）
    from sqlalchemy import text
    connection = op.get_bind()
    
    def safe_drop_index(index_name, table_name):
        """安全删除索引"""
        try:
            result = connection.execute(text("""
                SELECT 1 FROM pg_indexes 
                WHERE indexname = :index_name AND tablename = :table_name
            """), {"index_name": index_name, "table_name": table_name})
            if result.fetchone():
                op.drop_index(op.f(index_name), table_name=table_name)
        except Exception:
            pass  # 索引可能不存在，跳过
    
    def safe_create_index(index_name, table_name, columns, unique=False):
        """安全创建索引"""
        try:
            result = connection.execute(text("""
                SELECT 1 FROM pg_indexes 
                WHERE indexname = :index_name AND tablename = :table_name
            """), {"index_name": index_name, "table_name": table_name})
            if result.fetchone():
                return  # 索引已存在，跳过
        except Exception:
            pass  # 检查失败，继续尝试创建
        
        try:
            op.create_index(op.f(index_name), table_name, columns, unique=unique)
        except Exception as e:
            if "already exists" in str(e).lower() or "duplicate" in str(e).lower():
                pass  # 索引已存在，忽略
            else:
                raise
    
    # 安全删除 customer_service_chats 表的索引
    safe_drop_index('idx_customer_service_chats_is_ended', 'customer_service_chats')
    safe_drop_index('idx_customer_service_chats_service_id', 'customer_service_chats')
    safe_drop_index('idx_customer_service_chats_user_id', 'customer_service_chats')
    
    # 安全创建索引
    safe_create_index('ix_customer_service_chats_id', 'customer_service_chats', ['id'])
    
    # 安全删除 customer_service_messages 表的索引
    safe_drop_index('idx_customer_service_messages_chat_id', 'customer_service_messages')
    safe_drop_index('idx_customer_service_messages_created_at', 'customer_service_messages')
    
    # 安全创建索引
    safe_create_index('ix_customer_service_messages_id', 'customer_service_messages', ['id'])
    
    # 创建外键（如果不存在）
    try:
        op.create_foreign_key(None, 'messages', 'users', ['sender_id'], ['id'])
    except Exception:
        pass  # 外键可能已存在
    try:
        op.create_foreign_key(None, 'messages', 'users', ['receiver_id'], ['id'])
    except Exception:
        pass  # 外键可能已存在
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_index(op.f('ix_customer_service_messages_id'), table_name='customer_service_messages')
    op.create_index(op.f('idx_customer_service_messages_created_at'), 'customer_service_messages', ['created_at'], unique=False)
    op.create_index(op.f('idx_customer_service_messages_chat_id'), 'customer_service_messages', ['chat_id'], unique=False)
    op.drop_index(op.f('ix_customer_service_chats_id'), table_name='customer_service_chats')
    op.create_index(op.f('idx_customer_service_chats_user_id'), 'customer_service_chats', ['user_id'], unique=False)
    op.create_index(op.f('idx_customer_service_chats_service_id'), 'customer_service_chats', ['service_id'], unique=False)
    op.create_index(op.f('idx_customer_service_chats_is_ended'), 'customer_service_chats', ['is_ended'], unique=False)
    # ### end Alembic commands ###
