"""add_pending_user_table

Revision ID: add_pending_user_table
Revises: 2025_09_24_1221-618c4cce1eb7_add_missing_fields
Create Date: 2025-01-24 15:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'add_pending_user_table'
down_revision = '618c4cce1eb7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('hashed_password', sa.String(length=128), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('verification_token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pending_users_email', 'pending_users', ['email'], unique=True)
    op.create_index('ix_pending_users_expires', 'pending_users', ['expires_at'], unique=False)
    op.create_index('ix_pending_users_token', 'pending_users', ['verification_token'], unique=True)
    op.create_index(op.f('ix_pending_users_id'), 'pending_users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pending_users_id'), table_name='pending_users')
    op.drop_index('ix_pending_users_token', table_name='pending_users')
    op.drop_index('ix_pending_users_expires', table_name='pending_users')
    op.drop_index('ix_pending_users_email', table_name='pending_users')
    op.drop_table('pending_users')
    # ### end Alembic commands ###
