"""add_missing_fields

Revision ID: 618c4cce1eb7
Revises: 087ca9fb512c
Create Date: 2025-09-24 12:21:21.315258

"""
from alembic import op
import sqlalchemy as sa
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = '618c4cce1eb7'
down_revision: Union[str, Sequence[str], None] = '087ca9fb512c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_customer_service_chats_created_at', 'customer_service_chats', ['created_at'], unique=False)
    op.create_index('ix_customer_service_chats_is_ended', 'customer_service_chats', ['is_ended'], unique=False)
    op.create_index('ix_customer_service_chats_last_message_at', 'customer_service_chats', ['last_message_at'], unique=False)
    op.create_index('ix_customer_service_chats_service_id', 'customer_service_chats', ['service_id'], unique=False)
    op.create_index('ix_customer_service_chats_user_id', 'customer_service_chats', ['user_id'], unique=False)
    op.create_index('ix_customer_service_messages_chat_id', 'customer_service_messages', ['chat_id'], unique=False)
    op.create_index('ix_customer_service_messages_created_at', 'customer_service_messages', ['created_at'], unique=False)
    op.create_index('ix_customer_service_messages_sender_id', 'customer_service_messages', ['sender_id'], unique=False)
    op.create_index('ix_messages_created_at', 'messages', ['created_at'], unique=False)
    op.create_index('ix_messages_receiver_id', 'messages', ['receiver_id'], unique=False)
    op.create_index('ix_messages_sender_id', 'messages', ['sender_id'], unique=False)
    op.create_index('ix_messages_sender_receiver', 'messages', ['sender_id', 'receiver_id'], unique=False)
    op.create_index('ix_notifications_created_at', 'notifications', ['created_at'], unique=False)
    op.create_index('ix_notifications_is_read', 'notifications', ['is_read'], unique=False)
    op.create_index('ix_notifications_type', 'notifications', ['type'], unique=False)
    op.create_index('ix_notifications_user_id', 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_user_read', 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_index('ix_reviews_created_at', 'reviews', ['created_at'], unique=False)
    op.create_index('ix_reviews_task_id', 'reviews', ['task_id'], unique=False)
    op.create_index('ix_reviews_user_id', 'reviews', ['user_id'], unique=False)
    op.add_column('tasks', sa.Column('accepted_at', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('visibility', sa.String(length=20), nullable=True))
    op.create_index('ix_tasks_created_at', 'tasks', ['created_at'], unique=False)
    op.create_index('ix_tasks_deadline', 'tasks', ['deadline'], unique=False)
    op.create_index('ix_tasks_level_status', 'tasks', ['task_level', 'status'], unique=False)
    op.create_index('ix_tasks_location', 'tasks', ['location'], unique=False)
    op.create_index('ix_tasks_poster_id', 'tasks', ['poster_id'], unique=False)
    op.create_index('ix_tasks_poster_status', 'tasks', ['poster_id', 'status'], unique=False)
    op.create_index('ix_tasks_reward', 'tasks', ['reward'], unique=False)
    op.create_index('ix_tasks_status', 'tasks', ['status'], unique=False)
    op.create_index('ix_tasks_taker_id', 'tasks', ['taker_id'], unique=False)
    op.create_index('ix_tasks_taker_status', 'tasks', ['taker_id', 'status'], unique=False)
    op.create_index('ix_tasks_task_level', 'tasks', ['task_level'], unique=False)
    op.create_index('ix_tasks_task_type', 'tasks', ['task_type'], unique=False)
    op.create_index('ix_tasks_type_status', 'tasks', ['task_type', 'status'], unique=False)
    op.create_index('ix_users_created_at', 'users', ['created_at'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_index('ix_users_is_verified', 'users', ['is_verified'], unique=False)
    op.create_index('ix_users_name', 'users', ['name'], unique=False)
    op.create_index('ix_users_phone', 'users', ['phone'], unique=False)
    op.create_index('ix_users_user_level', 'users', ['user_level'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_user_level', table_name='users')
    op.drop_index('ix_users_phone', table_name='users')
    op.drop_index('ix_users_name', table_name='users')
    op.drop_index('ix_users_is_verified', table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_created_at', table_name='users')
    op.drop_index('ix_tasks_type_status', table_name='tasks')
    op.drop_index('ix_tasks_task_type', table_name='tasks')
    op.drop_index('ix_tasks_task_level', table_name='tasks')
    op.drop_index('ix_tasks_taker_status', table_name='tasks')
    op.drop_index('ix_tasks_taker_id', table_name='tasks')
    op.drop_index('ix_tasks_status', table_name='tasks')
    op.drop_index('ix_tasks_reward', table_name='tasks')
    op.drop_index('ix_tasks_poster_status', table_name='tasks')
    op.drop_index('ix_tasks_poster_id', table_name='tasks')
    op.drop_index('ix_tasks_location', table_name='tasks')
    op.drop_index('ix_tasks_level_status', table_name='tasks')
    op.drop_index('ix_tasks_deadline', table_name='tasks')
    op.drop_index('ix_tasks_created_at', table_name='tasks')
    op.drop_column('tasks', 'visibility')
    op.drop_column('tasks', 'accepted_at')
    op.drop_index('ix_reviews_user_id', table_name='reviews')
    op.drop_index('ix_reviews_task_id', table_name='reviews')
    op.drop_index('ix_reviews_created_at', table_name='reviews')
    op.drop_index('ix_notifications_user_read', table_name='notifications')
    op.drop_index('ix_notifications_user_id', table_name='notifications')
    op.drop_index('ix_notifications_type', table_name='notifications')
    op.drop_index('ix_notifications_is_read', table_name='notifications')
    op.drop_index('ix_notifications_created_at', table_name='notifications')
    op.drop_index('ix_messages_sender_receiver', table_name='messages')
    op.drop_index('ix_messages_sender_id', table_name='messages')
    op.drop_index('ix_messages_receiver_id', table_name='messages')
    op.drop_index('ix_messages_created_at', table_name='messages')
    op.drop_index('ix_customer_service_messages_sender_id', table_name='customer_service_messages')
    op.drop_index('ix_customer_service_messages_created_at', table_name='customer_service_messages')
    op.drop_index('ix_customer_service_messages_chat_id', table_name='customer_service_messages')
    op.drop_index('ix_customer_service_chats_user_id', table_name='customer_service_chats')
    op.drop_index('ix_customer_service_chats_service_id', table_name='customer_service_chats')
    op.drop_index('ix_customer_service_chats_last_message_at', table_name='customer_service_chats')
    op.drop_index('ix_customer_service_chats_is_ended', table_name='customer_service_chats')
    op.drop_index('ix_customer_service_chats_created_at', table_name='customer_service_chats')
    # ### end Alembic commands ###
