"""Initial migration: create all tables

Revision ID: 087ca9fb512c
Revises: 
Create Date: 2025-09-24 12:00:44.358693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '087ca9fb512c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 安全删除索引（如果存在）
    from sqlalchemy import inspect, text
    connection = op.get_bind()
    
    # 检查并删除 customer_service_chats 表的索引
    inspector = inspect(connection)
    try:
        indexes = [idx['name'] for idx in inspector.get_indexes('customer_service_chats')]
        if 'idx_customer_service_chats_is_ended' in indexes:
            op.drop_index(op.f('idx_customer_service_chats_is_ended'), table_name='customer_service_chats')
        if 'idx_customer_service_chats_service_id' in indexes:
            op.drop_index(op.f('idx_customer_service_chats_service_id'), table_name='customer_service_chats')
        if 'idx_customer_service_chats_user_id' in indexes:
            op.drop_index(op.f('idx_customer_service_chats_user_id'), table_name='customer_service_chats')
    except Exception:
        pass  # 表可能不存在，跳过
    
    # 安全创建索引（如果不存在）
    try:
        indexes = [idx['name'] for idx in inspector.get_indexes('customer_service_chats')]
        if 'ix_customer_service_chats_id' not in indexes:
            op.create_index(op.f('ix_customer_service_chats_id'), 'customer_service_chats', ['id'], unique=False)
    except Exception:
        # 如果表不存在或检查失败，尝试创建（可能会失败，但至少尝试了）
        try:
            op.create_index(op.f('ix_customer_service_chats_id'), 'customer_service_chats', ['id'], unique=False)
        except Exception:
            pass  # 索引可能已存在，跳过
    
    # 检查并删除 customer_service_messages 表的索引
    try:
        indexes = [idx['name'] for idx in inspector.get_indexes('customer_service_messages')]
        if 'idx_customer_service_messages_chat_id' in indexes:
            op.drop_index(op.f('idx_customer_service_messages_chat_id'), table_name='customer_service_messages')
        if 'idx_customer_service_messages_created_at' in indexes:
            op.drop_index(op.f('idx_customer_service_messages_created_at'), table_name='customer_service_messages')
    except Exception:
        pass  # 表可能不存在，跳过
    
    # 安全创建索引（如果不存在）
    try:
        indexes = [idx['name'] for idx in inspector.get_indexes('customer_service_messages')]
        if 'ix_customer_service_messages_id' not in indexes:
            op.create_index(op.f('ix_customer_service_messages_id'), 'customer_service_messages', ['id'], unique=False)
    except Exception:
        # 如果表不存在或检查失败，尝试创建（可能会失败，但至少尝试了）
        try:
            op.create_index(op.f('ix_customer_service_messages_id'), 'customer_service_messages', ['id'], unique=False)
        except Exception:
            pass  # 索引可能已存在，跳过
    
    # 创建外键（如果不存在）
    try:
        op.create_foreign_key(None, 'messages', 'users', ['sender_id'], ['id'])
    except Exception:
        pass  # 外键可能已存在
    try:
        op.create_foreign_key(None, 'messages', 'users', ['receiver_id'], ['id'])
    except Exception:
        pass  # 外键可能已存在
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_index(op.f('ix_customer_service_messages_id'), table_name='customer_service_messages')
    op.create_index(op.f('idx_customer_service_messages_created_at'), 'customer_service_messages', ['created_at'], unique=False)
    op.create_index(op.f('idx_customer_service_messages_chat_id'), 'customer_service_messages', ['chat_id'], unique=False)
    op.drop_index(op.f('ix_customer_service_chats_id'), table_name='customer_service_chats')
    op.create_index(op.f('idx_customer_service_chats_user_id'), 'customer_service_chats', ['user_id'], unique=False)
    op.create_index(op.f('idx_customer_service_chats_service_id'), 'customer_service_chats', ['service_id'], unique=False)
    op.create_index(op.f('idx_customer_service_chats_is_ended'), 'customer_service_chats', ['is_ended'], unique=False)
    # ### end Alembic commands ###
